### PR TITLE
Update typing of ref for React 18

### PR DESCRIPTION
**Pull request by anastasiiayeromina**

### CODE REVIEW

**Comment by thulstrup** [comment]
@anastasiiayeromina Thanks!
I do wonder if `HTMLDivElement` is too strict. Maybe a more generic `HTMLElement | null` is better?

**Comment by anastasiiayeromina** [comment]
@thulstrup agree. Your options seems much more flexible.
Fixed it already

**Comment by KittyGiraudel** [comment]
To keep compatibility with React 17, shall we use an union type of the old type and the new type?

**Comment by anastasiiayeromina** [comment]
@KittyGiraudel how do you like it now?

**Comment by KittyGiraudel** [comment]
Looks good. Can it be null though? @thulstrup Any reason you suggested to add `null`?

**Comment by anastasiiayeromina** [comment]
Hmm, at first I thought `null` would be useful as we usually initialise `useRef` with `null`...
But for my case it works well even without `null`.

**Comment by thulstrup** [comment]
`ref: (node: HTMLElement) => void` without `null` gave a TypeScript error.
`ref: (node: React.ReactNode | HTMLElement) => void` without `null` seems good.

**Comment by KittyGiraudel** [comment]
That’s because `null` is a valid value for `React.ReactNode`. :)

**Comment by anastasiiayeromina** [comment]
Updated

**Pull request merged**
